# runme: ansible-playbook -i plaintext-nutanix.yaml playbook_cleanup.yml
---
- hosts: ansiblerole_webservers
  remote_user: centos
  tasks:
  - name: ensure apache is installed and at the latest version
    yum: name=httpd state=latest
    notify:
    - restart apache
    become: yes
    become_method: sudo
  - name: enable and start apache
    service: name=httpd state=started enabled=yes
    become: yes
    become_method: sudo
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      become: yes
      become_method: sudo