# runme graph: ansible-inventory -i nutanix.yml --graph --vault-password-file vault_password_file
# runme list: ansible-inventory -i nutanix.yml --list --vault-password-file vault_password_file

plugin: grdavies.nutanix.prism_inventory
connections:
- ip_address: '172.23.0.7'
  password: 'nx2Tech100!'
  include_vms: 'yes'
  validate_certs: 'no'

